# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - working-directory: ./pigeonmark-utils
      run: npm ci
    - working-directory: ./pigeonmark-utils
      run: npm run build --if-present
    - working-directory: ./pigeonmark-utils
      run: npm test
    - working-directory: ./pigeonmark-html
      run: npm ci
    - working-directory: ./pigeonmark-html
      run: npm run build --if-present
    - working-directory: ./pigeonmark-html
      run: npm test
    - working-directory: ./pigeonmark-xml
      run: npm ci
    - working-directory: ./pigeonmark-xml
      run: npm run build --if-present
    - working-directory: ./pigeonmark-xml
      run: npm test
    - working-directory: ./pigeonmark-arbitrary
      run: npm ci
    - working-directory: ./pigeonmark-arbitrary
      run: npm run build --if-present
    - working-directory: ./pigeonmark-arbitrary
      run: npm test
